# Only for local test
version: "3.7"
services:
  colors:
    build: .
    command: "./wait-for.sh postgres:5432 -- ./entrypoint.sh"
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DIALECT: postgres
      DB_NAME: colors
      DB_USERNAME: postgres
      DB_PASSWORD: root
      JWT_SECRET: seckret
      JWT_EXPIRATION: 3600
      X-API-KEY: prueba
    depends_on:
      - postgres
  # Database Postgres
  postgres:
    image: "postgres:12.2-alpine" # use latest official postgres version
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: colors
    volumes:
      - ~/database_docker_volume/postgres:/var/lib/postgresql/data/ # persist data even
